# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Katherine Lee
title: Baker / Neuroscientist
email: katherine@katiebrains.com
website: katiebrains.com

# Dark Mode (true/false/never)
darkmode: true

# Social links
# twitter_username: facespics
# github_username:  sproogen
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jameswgrant
linkedin_username: kath-lee
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
additional_links:
- title: katiebrains.com
  icon: fas fa-globe
  url: https://katiebrains.com
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About sMe
about_profile_image: images/avatar.png
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Katie and I'm a recent Coginitive Science grad. Outside of academia, I have worked in the restaurant business since I was 16. I enjoy photography, art and traveling.

  I am most skilled in: <mark>Problem solving</mark> and <mark>making cupcakes</mark>

content:
  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: University of Arizona
        caption: August 2020
        sub_title: Bacheleor's of Scince in Neuroscience and Cognitive Science
        description: | # this will include new lines to allow paragraphs
          *	Magna Cum Laude
          *	Tau Sigma National Honor Society Member 
          *	Arizona Science Engineering and Mathematics Scholars (ASEMS) Member
          *	University of Arizona Honors College Member
      - layout: left
        title: Yavapai College
        caption: Decemeber 2018
        sub_title: Associates of Science
        description: | # this will include new lines to allow paragraphs
          *	GPA: 3.53


  - title: Work Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Saint Cupcake
        link: www.saintcupcake.com
        link_text: saintcupcake.com
        sub_title: Sales, Baker & Decorator
        caption: September '21 - October '22<br />Portland, OR          
        description: | # this will include new lines to allow paragraphs
            *	Utilized previous back-of-house experience, and personal love of baking to transition from counter sales to Bake and Decorator roles
            *	Prepped, baked and iced over 1200 cupcakes per day to exacting standards 
            *	Decorated customer cakes as per customer specifications
            *	Rapidly advanced in role and began training new bakers 

      - layout: left
        title: Madams Jams
        sub_title: Vendor Sales Associate
        caption: June '21 - September '21<br />Denver, CO           
        description: | # this will include new lines to allow paragraphs
            *	Greet and pitch product to 100+ customers daily 
            *	Consistently produce $400 in sales at 3 different markets


      - layout: left
        title: Muddy Buck Cafe
        link: muddybuckcoffeehouse.com
        link_text: Muddy Buck Coffee House
        sub_title: Manager
        caption: June '20 - June '21<br />Evergreen, CO           
        description: | # this will include new lines to allow paragraphs
            * Manage 6 team members and delegate responsibilities to keep labor under 32 hours/daily
            * Configured and optimized Square Point-of-Sale kiosks and reporting
            * Receive and deliver payment for semi-weekly food and alcohol orders
            * Mediation of customer dissatisfaction, and handling of employee relations
            * Execute preparation of 45+ food and beverage orders per hour during peak season


      - layout: left
        title: Arizona Catering Company
        link: union.arizona.edu/catering/
        link_text: Arizona Catering Company
        sub_title: Catering Server
        caption: January '19 - May '19<br />Tucson, AZ           
        description: | # this will include new lines to allow paragraphs
            * Presented 3 course meals for up to 800 VIP guests at University events 
            * Butlered Hors d’ Oeuvres at private presidential events 



      - layout: left
        title: Olive Garden
        link: olivegarden.com
        link_text: olivegarden.com
        sub_title: Server
        caption: July '17 - December '18<br />Prescott, AZ           
        description: | # this will include new lines to allow paragraphs
            *	Provided superior customer service 
            *	Ranked in top five of beverage sales for a month streak


  - title: Academic Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: University of Arizona
        link: arizona.edu
        link_text: arizona.edu
        sub_title: ASEMS-T Peer Mentor
        caption: September '21 - October '21 <br />Tucson, AZ  
        description: | # this will include new lines to allow paragraphs
            *	Coordinated bi-weekly in person and virtual student meetings for 10 students to reinforce academic and personal progress while taking a full course load 
            *	Advised students in study schedules and administrative processes 


      - layout: left
        title: University of Arizona
        link: https://asems.arizona.edu/
        link_text: ASEMS Scholars Program
        sub_title: Research assistant<br />Learning, Language, Literacy, And Lexicon Lab
        caption: January '19 - May '20 <br />Tucson, AZ  
        description: | # this will include new lines to allow paragraphs
            *	Administered working memory games to kindergartners with speech impairments and recorded data 3 times a week 
            *	Developed video and written training material for data collectors 
            *	Navigated network of 5 schools to coordinate up child interactions 


      - layout: left
        title: University of Michigan Research Experiences for Undergraduates Program	
        link: https://neuroscience.med.umich.edu/reu-site-summer-intensive-research-experiences-neuroscience-siren
        link_text: Summer Intensive Research Experiences in Neuroscience
        sub_title: Research Assistant<br />Translation & Developmental Lab
        caption: September '21 - October '21<br />Ann Arbor, MI
        description: | # this will include new lines to allow paragraphs
            *	Analyzed structural brain data and behavioral data using R programing language
            *	Presented findings in poster session as well as a live presentation for Neuroscience faculty


      - layout: left
        title: Yavapai College
        link: yc.edu
        link_text: yc.edu
        sub_title: Lab Assistant<br />Chemistry Department
        caption: August '17 - May '18<br />Prescott, AZ
        description: | # this will include new lines to allow paragraphs
            *	Prepared solutions and standards for multiple classes labs per formulas and directions
            *	Maintained and calibrated a variety of laboratory equipment, including Nuclear Magnetic Resonance machine, Gas Chromatographs, various spectroscopy equipment, and microgram scales
            *	Recovered solvents and performed a variety of laboratory procedures and chemical synthesis


  # - title: Projects # Title for the section
  #   layout: list # Type of content section (list/text)
  #   content:
  #     - layout: top-middle
  #       title: Super awesome project
  #       link: github.com/sproogen
  #       # link_text: Project Website
  #       additional_links:
  #         - title:  sproogen/modern-resume-theme
  #           icon: fab fa-github
  #           url: github.com/sproogen/modern-resume-theme
  #         # - title:  Github page for project (eg. sproogen/modern-resume-theme)
  #         #   icon: fab fa-github
  #         #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
  #       quote: >
  #         This is probably one of the greatest apps ever created, if you don't agree you're probably wrong.
  #       description: | # this will include new lines to allow paragraphs
  #         I started this project as a way if learning <mark>React</mark> and it has since grown into a fully fledged app. I have learned many skills through this and been I'm very proud of having this in my portfolio. If you don't have a project as awesome as this I would advise you make one.



  - title: Awards & Nominations
    layout: list
    content:
      - layout: top-left
        # title: 
        sub_title: Provost Award | Nomination
        caption: February '20
        description: | # this will include new lines to allow paragraphs
            Nomination by Lupita Mendez, Program Manager & Transfer Specialist ASEMS Scholars Program, University of Arizona

      - layout: top-left
        sub_title: S-STEM Symposium Travel Award 
        caption: September '19
        description: | 
            Nomination by Dr. Katrina Miranda, Department of Chemistry and Biochemistry, University of Arizona

      - layout: top-left
        sub_title: S-STEM Scholarship 
        caption: August '18
        description: | 
            $10,000 supported by NSF grant 



  - title: Memberships
    layout: list
    content:
      - layout: top-left
        sub_title: April '19
        description: | 
          Tau Sigma National Honor Society
      - layout: top-left
        sub_title: August '18
        description: | 
          Arizona Science Engineering And Mathematics Scholars (ASEMS)
      - layout: top-left
        sub_title: August '18
        description: | 
          University Of Arizona Honors College


  - title: Professional Development
    layout: list
    content:
      - layout: top-left
        sub_title: University Of Arizona
        caption: Attendee<br />January '20
        description: |
          Launching Your Career In Stem

      - layout: top-left
        sub_title: University Of Arizona
        caption: Presenter<br />November '19
        description: |
          Asems Research Symposium

      - layout: top-left
        sub_title: University Of Arizona
        caption: Panelist<br />October '19
        description: |
          Undergraduate Research Panel

      - layout: top-left
        sub_title: Chicago
        caption: Attendee<br />October '19
        description: |
          Society For Neuroscience

      - layout: top-left
        sub_title: Washington D.C.
        caption: Attendee<br />September '19
        description: |
          S-Stem Symposium

      - layout: top-left
        sub_title: University Of Michigan
        caption: Presenter<br />August '19
        description: |
          Siren/Nuro Final Symposium




# Footer
footer_show_references: false
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
